package com.fpt.idoctor.model;
// Generated Mar 8, 2018 8:26:25 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Disease generated by hbm2java
 */
@Entity
@Table(name = "disease")
public class Disease implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private Age age;
	private Specialty specialty;
	private Symptom symptom;
	private String name;
	private String overview;
	private String detail;
	private Boolean sex;

	public Disease() {
	}

	public Disease(Long id) {
		this.id = id;
	}

	public Disease(Long id, Age age, Specialty specialty, Symptom symptom,
			String name, String overview, String detail, Boolean sex) {
		this.id = id;
		this.age = age;
		this.specialty = specialty;
		this.symptom = symptom;
		this.name = name;
		this.overview = overview;
		this.detail = detail;
		this.sex = sex;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "ageId")
	public Age getAge() {
		return this.age;
	}

	public void setAge(Age age) {
		this.age = age;
	}

	@ManyToOne
	@JoinColumn(name = "specialtyId")
	public Specialty getSpecialty() {
		return this.specialty;
	}

	public void setSpecialty(Specialty specialty) {
		this.specialty = specialty;
	}

	@ManyToOne
	@JoinColumn(name = "symptomId")
	public Symptom getSymptom() {
		return this.symptom;
	}

	public void setSymptom(Symptom symptom) {
		this.symptom = symptom;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "overview", length = 300)
	public String getOverview() {
		return this.overview;
	}

	public void setOverview(String overview) {
		this.overview = overview;
	}

	@Column(name = "detail", length = 500)
	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	@Column(name = "sex")
	public Boolean getSex() {
		return this.sex;
	}

	public void setSex(Boolean sex) {
		this.sex = sex;
	}

}
