package com.fpt.idoctor.model;
// Generated Mar 8, 2018 8:26:25 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fpt.idoctor.bean.SymptomBean;

/**
 * Symptom generated by hbm2java
 */
@Entity
@Table(name = "symptom")
public class Symptom implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private String name;
	private Set<Disease> diseases = new HashSet<Disease>(0);

	public Symptom() {
	}

	public Symptom(Long id) {
		this.id = id;
	}

	public Symptom(Long id, String name, Set<Disease> diseases) {
		this.id = id;
		this.name = name;
		this.diseases = diseases;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(mappedBy = "symptom")
	public Set<Disease> getDiseases() {
		return this.diseases;
	}

	public void setDiseases(Set<Disease> diseases) {
		this.diseases = diseases;
	}

	public SymptomBean convertToBean() {
		SymptomBean bean = new SymptomBean();
		bean.setId(id);
		bean.setName(name);
		return bean;
	}

}
